### PR TITLE
36 check backend version

### LINKED ISSUE #36: Check backend version
Add a file that contains the required backend version (the commit oid or the tag).
Check the version on startup and fail if the versions don't match.

See https://github.com/ontohub/ontohub-backend/issues/44

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #36.

### CODE REVIEW

File: config/environment.js [hunk 1]
```diff
@@ -23,12 +23,19 @@ module.exports = function(environment) {
...
-    }
+    };
     // ENV.APP.LOG_RESOLVER = true;
     // ENV.APP.LOG_ACTIVE_GENERATION = true;
     // ENV.APP.LOG_TRANSITIONS = true;
     // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
     // ENV.APP.LOG_VIEW_LOOKUPS = true;
+    ENV.versionConfig = {
+      tag: '0.0.0',
+      commitsSinceTagMin: '65',
```
Comment (phyrog) [inline config/environment.js]: Why strings instead of numbers?

Comment (eugenk) [inline config/environment.js]: Because I'm stupid. This is fixed by commit --amend.

File: mirage/fixtures/versions.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+export default {
```
Comment (phyrog) [inline mirage/fixtures/versions.js]: I think we dont need this file since the version is hardcoded in `mirage/config.js`.

File: mirage/scenarios/default.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import _ from 'lodash';
 
 export default function(server) {
-
+  server.loadFixtures('versions');
```
Comment (phyrog) [inline mirage/scenarios/default.js]: Should be removed too if the version fixtures are removed.
